# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            ChainsX
tagline:          'blog'
description:      'My personal blog.'
url:              https://chainsx.cn
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Ian Brunelli
  url:            https://google.com/+pzhrhlx

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:

  - icon:         github
    url:          https://github.com/chainsx
    desc:         follow me on github

  - icon:         googleplus-alt
    url:          https://google.com/+pzhrhlx
    desc:         Add me on google+


menu:
  - title:        主页
    url:          /

  - title:        关于
    url:          /about

copyright:
  author:         ChainsX
  url:            https://chainsx.github.io
  type_title:     home page
  type_url:       https://chainsx.cn

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
